### ISSUE TITLE
website icon error

### ISSUE THREAD

**Issue by 619dev** [TobiasMarschner/ferrishare#3]
<img width="1090" alt="截屏2024-12-29 12 22 31" src="https://github.com/user-attachments/assets/e62c94a6-9aa0-47f2-9a89-6e17d71a724b" />

**Comment by 619dev** [comment]
change to 1.0.0 images,it fixed.

**Comment by 619dev** [comment]
change to 1.0.1 ， not images problem，just case by cdn

**Comment by TobiasMarschner** [comment]
None of the webfonts are loaded in the screenshot you provided, and from the version string at the bottom I conclude you built from source. I had another look at the provided instructions and suspect you cloned the repository without having [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) installed on your machine.

Git LFS is used in the project to manage (large) binary assets, especially webfonts and images. I updated the "build from source" instructions to make it clear that you need to have Git LFS installed when cloning, or that you can alternatively download the source archive from the [releases page]() where the LFS assets are included automatically.
