### ISSUE TITLE
Please provide a nginx profile template

### ISSUE THREAD

**Issue by 619dev** [TobiasMarschner/ferrishare#5]
Compile and run with source code, 
cargo run-- release
pls give me a nginx template
Traefik confuses me.

**Comment by TobiasMarschner** [comment]
Not planned. Official examples are provided for Traefik as it's the option I have the most experience with. There are countless guides and tutorials on the internet on how to setup nginx as a reverse proxy, please use them.

If someone else wants to provide a working and tested docker compose file that uses a different reverse proxy, I'll gladly add it as an additional resource to the repo and link it in the README.
